name = "DigitalPower"
license = "MIT"
licenselink = ""
description = "数字化转型"
homepage = ""
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'gethugothemes', 'typography']
features = ['bootstrap','responsive']
min_version = "0.58.0"
DefaultContentLanguage = "en"
[languages]
  [languages.en]
    title = "DigitalPower"
    languageName = "English"
    weight = 1
    [languages.cn]
    title = "数字生产力"
    languageName = "Chinese"
    weight = 2
[author]
  name = "AgileFan"
  homepage = ""
  [params]
  [params.navigation]
    help = "Help"
